//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _125_BCCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentService
    {
        public int AppointmentServiceId { get; set; }
        public int AppointmentId { get; set; }
        public int ServiceId { get; set; }
        public decimal ServicePrice { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Service Service { get; set; }
    }
}
