//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _125_BCCK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PetCareDBEntities1 : DbContext
    {
        public PetCareDBEntities1()
            : base("name=PetCareDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentService> AppointmentServices { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VaccinationRecord> VaccinationRecords { get; set; }
        public virtual DbSet<WorkSchedule> WorkSchedules { get; set; }
    
        public virtual ObjectResult<sp_GetBookedTimeSlots_Result> sp_GetBookedTimeSlots(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBookedTimeSlots_Result>("sp_GetBookedTimeSlots", dateParameter);
        }
    
        public virtual ObjectResult<sp_GetCustomerAppointments_Result> sp_GetCustomerAppointments(Nullable<int> customerId, string status)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCustomerAppointments_Result>("sp_GetCustomerAppointments", customerIdParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_GetRevenueReport_Result> sp_GetRevenueReport(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRevenueReport_Result>("sp_GetRevenueReport", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_GetTopServices_Result> sp_GetTopServices(Nullable<int> topN)
        {
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTopServices_Result>("sp_GetTopServices", topNParameter);
        }
    }
}
