//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _125_BCCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationRecord
    {
        public int RecordId { get; set; }
        public int PetId { get; set; }
        public int AppointmentId { get; set; }
        public string VaccineName { get; set; }
        public System.DateTime VaccinationDate { get; set; }
        public Nullable<System.DateTime> NextDueDate { get; set; }
        public string Notes { get; set; }
        public int StaffId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual User User { get; set; }
    }
}
