//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _125_BCCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public int ScheduleId { get; set; }
        public string DayOfWeek { get; set; }
        public System.TimeSpan OpenTime { get; set; }
        public System.TimeSpan CloseTime { get; set; }
        public bool IsClosed { get; set; }
    }
}
